name: build frontend

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yaml'
    branches:
      - main

jobs:
  build:
    name: "frontend:build"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: docker/setup-qemu-action@v2
        - uses: docker/setup-buildx-action@v2
        - uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - uses: docker/build-push-action@v3
          with:
            context: ./frontend
            file: ./frontend/Dockerfile
            platforms: linux/arm64, linux/amd64
            push: true
            tags: ghcr.io/16elp/KubeFunApp:frontend-${{ github.sha }}

  tests:
    name: "frontend:test"
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@vs
      - uses: docker/login-action@v2
        with:
          registry: ghrc.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: pull and run tests
        run: |
          docker pull ghcr.io/16elp/KubeFunApp:frontend-${{ github.sha }}
          docker run -d -p 2000:2000 -e PORT=2000 ghcr.io/16elp/KubeFunApp:frontend-${{ github.sha }}
          sleep 10
          curl localhost:2000/api/status
          exit $?
    - name: push image
        run: |
          docker tag ghrc.io/16elp/KubeFunApp:frontend-${{ github.sha }} ghcr.io/16elp/KubeFunApp:frontend
          docker push ghcr.io/16elp/KubeFunApp:frontend



